apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-alb
  labels:
    app.kubernetes.io/name: external-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-00562dc8bb6008242,subnet-035a36563bef13dc9,subnet-02903e1643b36d542
    alb.ingress.kubernetes.io/target-type: instance
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: front
              servicePort: 80